### ISSUE TITLE
VnV Review_Indentation Issue

### ISSUE THREAD

**Issue by kypss94132** [tanya-jp/ANN-CAS741#19]
In Section 3.5, the indentation of the paragraphs is inconsistent. Some sentences are indented, while others are not.

**Comment by tanya-jp** [comment]
@kypss94132 Thanks for your comment! The section you're referring to uses itemization in LaTeX, which inherently indents bullet points for clarity and distinction. This is standard formatting for itemized lists in LaTeX. If there's a specific part of the section that you find inconsistent or unclear, could you please specify? I'd be happy to make further adjustments if needed.

**Comment by kypss94132** [comment]
Hi, Tanya. I found out there’s a typo in my previous feedback. The section I indicated should be 3.7. 
Thank you for letting me know, and I apologize for any confusion caused.
