### ISSUE TITLE
Modules consistency MG+MIS

### ISSUE THREAD

**Issue by CynthiaLiu0805** [tanya-jp/ANN-CAS741#26]
There are lots of modules in your project so I think it might be helpful to order modules logically? Also in your use hierarchy in MG, the Input Preparing and Preprocessing Modul uses the Input Image Module, but this is not shown in the MIS (Section 12.2)

**Comment by tanya-jp** [comment]
Thank you so much for this issue!
I tried to start from top and go to bottom. Also, about the other thing I fixed it during implementation 
 that you can see in this commit 93dd05046f47d2a3deda20532cdaee9f0836313d .
