### ISSUE TITLE
Transition in MIS

### ISSUE THREAD

**Issue by CynthiaLiu0805** [tanya-jp/ANN-CAS741#27]
If I am understanding correctly from the checklist, the transition in Access Routine Semantic is referred to the change of the states. But I think in your MIS, some transitions are more like explanation of function. Probably that is because of the phrasing, maybe you could consider adjusting that?

**Comment by tanya-jp** [comment]
I think this has been fixed in this version 93dd05046f47d2a3deda20532cdaee9f0836313d . If you have any further suggestions please let me know! Thanks for your time and comment!
