### ISSUE TITLE
MIS local functions

### ISSUE THREAD

**Issue by CynthiaLiu0805** [tanya-jp/ANN-CAS741#28]
How are the local functions used in sections 12.4.5 and 13.4.5? I might be wrong but I thought they should be related to the export access program somehow. Feel like the local functions you write are more like the functions you are going to implement in the software. 
Also, there are functions rgb2gray, prep pixels, and flat data in both 12.4.5 and 13.4.5 with the same name, are they going to be overwritten?

**Comment by tanya-jp** [comment]
I added more details for these two parts. I think know it is not ambiguous like before. I appreciate your comment!
 Also, about the second part, yes they are going to use the Data Preparing and Preprocessing Module methods' results as their parent.
