### ISSUE TITLE
Problem statement

### ISSUE THREAD

**Issue by tanya-jp** [tanya-jp/ANN-CAS741#3]
Hi Dr. Smith,

Please review my problem statement. 
https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf

Thanks

**Comment by smiths** [comment]
Feedback:

- You can make the [link to your problem statement](https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf) look nicer with markdown
- I would have liked to see some equations in the problem statement.  You'll want theoretical models that define what machine learning is in your SRS
- the choice of Python is not abstract.  You don't have to make that choice this early in the process.  The environment should be the Operating Systems that you will support
- Goals should be in a list, not in a paragraph

Your project is approved.  I'm looking forward to learning more about it.

**Comment by tanya-jp** [comment]
@smiths Thanks for approval and your feedback!
- The equations are shown in the [GitHub link mentioned in the problem statement](https://github.com/tanya-jp/CIFAR-Classification/blob/main/CIFAR_ANN.ipynb)
- The Environment and Goals are edited based on your comments
- Edited problem statement can be found [Here.](https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/ProblemStatementAndGoals/ProblemStatement.pdf)
