### ISSUE TITLE
MG - Missing Modules in Traceability Matrix 

### ISSUE THREAD

**Issue by rnorouziani** [tanya-jp/ANN-CAS741#31]
In the documentation, certain modules are missing from the traceability sections. Specifically, modules M7, M9, and M10 in the table 2, and M2, M3, M8, and M9 in the table 3. Including these could provide a complete overview of module interactions and responsibilities.

**Comment by tanya-jp** [comment]
Thanks for your suggestion!
I edited table2. However, in table 3, the point is for each of the changes only one module should be changed.
