### ISSUE TITLE
MIS -Independent Module for Connecting Input and Output Modules

### ISSUE THREAD

**Issue by rnorouziani** [tanya-jp/ANN-CAS741#32]
To improve modularity, it's suggested to connect the Input and Output Modules via an independent module, such as a Control Module, rather than integrating the Input Module directly within the Control Module. This could clarify module interactions and responsibilities.

**Comment by tanya-jp** [comment]
Thanks for your comment Reyhaneh!
Actually, the input module is not connected to the control module directly. Also, the output module is just for showing the class and receiving user's feedback. Although I believe this design satisfies this matter, if you have any other idea, please let me know.
