### ISSUE TITLE
VnV - Clarify "Y" and "N" in Table 1

### ISSUE THREAD

**Issue by rnorouziani** [tanya-jp/ANN-CAS741#35]
In Table 1, under the "Valid?" column, the letters "Y" and "N" are used but not defined. It's recommended to define "Y" (Yes) and "N" (No) in the "Symbols, Abbreviations, and Acronyms" section to clarify their meaning.

**Comment by tanya-jp** [comment]
Thanks for your comment Reyhaneh! I think you mean Table 2. I fixed that table.
