### ISSUE TITLE
VnV - Hyperlink Document Names

### ISSUE THREAD

**Issue by rnorouziani** [tanya-jp/ANN-CAS741#37]
Hyperlink the document names instead of the author names for easier access to the documents.

**Comment by tanya-jp** [comment]
Thanks for your recommendation Reyhaneh! Actually, I have not hyperlinked the authors' names. I have just included the citations. By clicking on the hyperlinked names, you will get the references part. I did this way, so if someone is reading the documents offline, they can find the reference of these parts.
