### ISSUE TITLE
VnV - Limited Data Type Handling in Input Verification Test

### ISSUE THREAD

**Issue by rnorouziani** [tanya-jp/ANN-CAS741#38]
The Input Verification Test focuses on specific data types, but it's unclear how the system handles other, unspecified data types. It is better to throw an exception for any data type not explicitly listed as valid in the verification test to enhance error handling.

**Comment by tanya-jp** [comment]
Thank you so much for your comment!
As you can see, TC-ANN-3 and TC-ANN-6 are test cases for invalid data types. Since this table includes different test cases, I think this is not needed to have all of the unacceptable data types.
