### ISSUE TITLE
SRS

### ISSUE THREAD

**Issue by tanya-jp** [tanya-jp/ANN-CAS741#4]
Dr. @smiths please review my [SRS](https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/SRS/SRS.pdf). Thanks!

**Comment by smiths** [comment]
[TanyaDjavaherpour_SRS.pdf](https://github.com/tanya-jp/ANN-CAS741/files/14390923/TanyaDjavaherpour_SRS.pdf)

The feedback is attached.  You may wish to create issues from the feedback to organize your work and clearly show the changes between the current version and the final version.  The grade will be posted on Avenue soon.

**Comment by tanya-jp** [comment]
Hi Dr. @smiths ,

Thank you so much for the valuable comments. 

[TanyaDjavaherpour_SRS.pdf](https://github.com/tanya-jp/ANN-CAS741/files/14912741/TanyaDjavaherpour_SRS.pdf)

I read all of your comments carefully and tried to apply all of them. However, for some of them I had different ideas, that I wrote them in the attached document. 

Thank you again for your help and support!

Regards,
Tanya
