### ISSUE TITLE
SRS review

### ISSUE THREAD

**Issue by tanya-jp** [tanya-jp/ANN-CAS741#5]
@AtiyehSayadi please review my [SRS](https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/SRS/SRS.pdf). Thanks!

**Comment by AtiyehSayadi** [comment]
Thank you for inviting me to review your SRS file. Your document was very precise and beautifully organized, but it seems that there are only a few areas that require more attention:

1. In the measurement units table in section 1.1, you might consider including pixels for when the input is an image.
2 .Contrary to what is stated in the text, the "Table of Symbols" is not arranged alphabetically.
3. In the reference section, all sources mentioned in the text should be displayed.
4. Earlier, you mentioned that your matrix is a 3D matrix, but later in section 4.2.4, it is stated to be a 2D matrix, which appears to be inconsistent.
5. There is no explanation provided regarding the size of input images and how many kilobytes or megabytes they can be.
6. There is no explanation provided regarding the format of the input image, such as .PNG or any other type.

If you have any questions, please don't hesitate to ask.
Atiyeh

**Comment by AtiyehSayadi** [comment]
Thank you for inviting me to review your SRS file. Your document was very precise and beautifully organized, but it seems that there are only a few areas that require more attention:

1. In the measurement units table in section 1.1, you might consider including pixels for when the input is an image.
2. Contrary to what is stated in the text, the "Table of Symbols" is not arranged alphabetically.
3. In the reference section, all sources mentioned in the text should be displayed.
4. Earlier, you mentioned that your matrix is a 3D matrix, but later in section 4.2.4, it is stated to be a 2D matrix, which appears to be inconsistent.
5. There is no explanation provided regarding the size of input images and how many kilobytes or megabytes they can be.
6. There is no explanation provided regarding the format of the input image, such as .PNG or any other type.

If you have any questions, please don't hesitate to ask.
Atiyeh

**Comment by smiths** [comment]
@AtiyehSayadi in the future, please create separate new issues for each of your comments.

**Comment by tanya-jp** [comment]
Hi @AtiyehSayadi ,

Thank you so much for taking the time to review my documentation and for your kind words. I really appreciate it!

I have implemented four of your suggestions in my SRS, which you can view through the commits or at [HERE](https://github.com/tanya-jp/ANN-CAS741/blob/main/docs/SRS/SRS.pdf). Regarding point 5, as mentioned in the document, the size of input images depends on the size of the training data (mxn), which in this case is 32x32. Since this is already included in the document, I haven't made any additional changes in response to this point. Based on my explanation, do you feel this is sufficient, or do you still think an explicit mention is necessary?

Thanks again for your valuable feedback!

Best,
Tanya

**Comment by AtiyehSayadi** [comment]
Dear Tanya,

 Your SRS file was excellently written .Everything looked good. Tank you!

Atiyeh
